##### COLUMNS NAMES FOR DATAFRAMES #####
INT_PERIOD = "int_period"
INT_NUM_BLOQ = "int_num_bloq"
INT_NUM_TRAMO = "int_num_tramo"
INT_NUM_GRUPO_EXCL = "int_num_grupo_excl"

INT_NUM_TRAMO_PARENT = "int_num_tramo_parent"
INT_NUM_TRAMO_CHILD = "int_num_tramo_child"
INT_NUM_BLOQ_PARENT = "int_num_bloq_parent"
INT_NUM_BLOQ_CHILD = "int_num_bloq_child"

CAT_BIDDING_ZONE = "cat_bidding_zone"
CAT_OFERTADA_CASADA = "cat_ofertada_casada"
CAT_ORDER_TYPE = "cat_order_type"
CAT_FRONTIER = "cat_frontier"
CAT_BUY_SELL = "cat_buy_sell"

FLOAT_IMPORT_CAPACITY = "float_import_capacity"
FLOAT_EXPORT_CAPACITY = "float_export_capacity"
FLOAT_BID_POWER = "float_bid_power"
FLOAT_BID_PRICE = "float_bid_price"
FLOAT_PRICE_FR = "float_price_fr"
FLOAT_MIC = "float_mic"
FLOAT_MAX_POWER = "float_max_power"
FLOAT_BID_PRICE = "float_bid_price"
FLOAT_BID_POWER = "float_bid_power"
FLOAT_BID_POWER_CUMSUM = "float_bid_power_cumsum"
FLOAT_BID_POWER_CUMSUM_BY_COUNTRY = "float_bid_power_cumsum_by_country"
FLOAT_MAV = "float_mav"
FLOAT_MAR = "float_mar"

ID_UNIDAD = "id_unidad"
ID_ORDER = "id_order"
ID_INDIVIDUAL_BID = "id_individual_bid"
ID_BLOCK_ORDER = "id_block_order"
ID_SCO = "id_sco"
ID_COMPLEX_ORDER = "id_complex_order"
ID_BLOCK_ORDER_PARENT = "id_block_order_parent"
ID_BLOCK_ORDER_CHILD = "id_block_order_child"
ID_SCO_PARENT = "id_sco_parent"
ID_SCO_CHILD = "id_sco_child"

BOOL_IS_SIMPLE_BID = "bool_is_simple_bid"
BOOL_IS_SCO = "bool_is_sco"
BOOL_IS_NOT_EXCLUSIVE_GROUP = "bool_is_not_exclusive_group"
BOOL_IS_EXCLUSIVE_GROUP = "bool_is_exclusive_group"

DATE_SESION = "date_sesion"
DATETIME_SESION = "datetime_sesion"

IDS_MIC_SCOS = "ids_mic_scos"
INT_MIC_SCOS_COUNT = "int_mic_scos_count"
IDS_BID_BLOCKS = "ids_bid_blocks"
INT_BID_BLOCKS_COUNT = "int_bid_blocks_count"
BOOL_ARE_PARADOXAL_ORDERS_TESTED = "bool_are_paradoxal_orders_tested"
BOOL_IS_EXPECTED_INCOME_RESPECTED = "bool_is_expected_income_respected"
ID_PARADOXAL_ORDERS = "id_paradoxal_orders"
PARADOXAL_ORDERS_COLUMN = "paradoxal_orders"
IDS_PARADOXAL_ORDERS = (
    "ids_paradoxal_orders"  # id_order if mic_sco, id_block_order if bid_block
)
INT_PARADOXAL_ORDERS_COUNT = "int_paradoxal_orders_count"

FLOAT_VARIABLE_COST = "float_variable_cost"
FLOAT_TOTAL_VARIABLE_COST = "float_total_variable_cost"
FLOAT_FIX_COST = "float_fix_cost"
FLOAT_CLEARED_POWER = "float_cleared_power"
FLOAT_CLEARED_POWER_CUMSUM = "float_cleared_power_cumsum"
FLOAT_CLEARED_POWER_CUMSUM_BY_COUNTRY = "float_cleared_power_cumsum_by_country"
FLOAT_CLEARED_PRICE = "float_cleared_price"
FLOAT_COLLECTION_RIGHTS = "float_collection_rights"
FLOAT_OBJECTIVE_VALUE = "float_objective_value"
FLOAT_RATIO_NET_INCOME_CLEARED_POWER = "float_ratio_net_income_cleared_power"
FLOAT_RATIO_NET_INCOME_BID_POWER = "float_ratio_net_income_bid_power"
FLOAT_NET_INCOME = "float_net_income"
FLOAT_MAXIMIZED_COMPETITIVE_BID_POWER = "float_maximized_competitive_bid_power"
SOLVER_RESULTS_COLUMN = "solver_results"
CLEARED_ENERGY_COLUMN = "cleared_energy"
CLEARING_PRICES_COLUMN = "clearing_prices"
SPAIN_PORTUGAL_TRANSMISSIONS_COLUMN = "spain_portugal_transmissions"
