import mibel_simulator.columns as cols


SPAIN_ZONE = "ES"
PORTUGAL_ZONE = "PT"

PAIS_OPTIONS = [SPAIN_ZONE, PORTUGAL_ZONE]

UNIDADES_SPLITTING_ZONE_COLUMN = "ZONA"
UNIDADES_ZONE_COLUMN = "ZONA/FRONTERA"
FRANCE_CODIGOUNIDAD = "MIEU"

FRONTIER_MAPPING = {
    2: "PT",
    3: "FR",
    4: "MA",  # MOROCCO
    5: "AD",  # ANDORRA
}

FRONTIER_MAPPING_REVERSE = {v: k for k, v in FRONTIER_MAPPING.items()}
CAT_FRONTIER_OPTIONS = list(FRONTIER_MAPPING.keys())


##### INTERNATIONAL UOFS #####

FRANCE_UOF = "MIEU"
SPAIN_UOF = "MIE"
PORTUGAL_UOF = "MIP"
INTERCONEXION_UOFS = [FRANCE_UOF, PORTUGAL_UOF, SPAIN_UOF]

FRANCE_ID_ORDER = "12345678901234"
FRANCE_ID_UNIDAD = "MIEU"

### CAT_PAIS_VALUES ###
CAT_PAIS_FRANCE = "FR"
CAT_PAIS_SPAIN = "ES"
CAT_PAIS_PORTUGAL = "PT"
CAT_PAIS_MIBEL = "MI"

CAT_BUY = "C"
CAT_SELL = "V"

BUY_SELL_OPTIONS = [CAT_BUY, CAT_SELL]

CAT_TIPO_OFERTA_SIMPLE = "S"
CAT_TIPO_OFERTA_SIMPLE_BLOCK = "C01"
CAT_TIPO_OFERTA_SCO = "C02"
CAT_TIPO_OFERTA_EXCLUSIVE_GROUP = "C04"
CAT_TIPO_OFERTA_EXPORT_FRANCE = "Exp FR"
CAT_TIPO_OFERTA_IMPORT_FRANCE = "Imp FR"
CAT_TIPO_OFERTA_EXPORT_PORTUGAL = "Exp PT"
CAT_TIPO_OFERTA_IMPORT_PORTUGAL = "Imp PT"
CAT_TIPO_OFERTA_IMPORT_SPAIN = "Imp ES"
CAT_TIPO_OFERTA_EXPORT_SPAIN = "Exp ES"

TIPO_OFERTA_OPTIONS = [
    CAT_TIPO_OFERTA_SIMPLE,
    CAT_TIPO_OFERTA_SIMPLE_BLOCK,
    CAT_TIPO_OFERTA_SCO,
    CAT_TIPO_OFERTA_EXCLUSIVE_GROUP,
    CAT_TIPO_OFERTA_EXPORT_FRANCE,
    CAT_TIPO_OFERTA_IMPORT_FRANCE,
    CAT_TIPO_OFERTA_EXPORT_PORTUGAL,
    CAT_TIPO_OFERTA_IMPORT_PORTUGAL,
    CAT_TIPO_OFERTA_IMPORT_SPAIN,
    CAT_TIPO_OFERTA_EXPORT_SPAIN,
]

##### OTHER CONSTANTS #####

BLOCK_UNIQUE_IDENTIFIERS = [
    cols.ID_ORDER,
    cols.INT_NUM_BLOQ,
]

DET_CAB_DATE_UNIQUE_IDENTIFIERS = [
    cols.INT_PERIODO,
    cols.CAT_BUY_SELL,
    cols.ID_ORDER,
    cols.INT_NUM_TRAMO,
    cols.INT_NUM_BLOQ,
    cols.INT_NUM_GRUPO_EXCL,
]

TRIALS_DF_COLUMNS = [
    cols.PARADOX_GROUPS_COLUMN,
    cols.IDS_MIC_SCOS,
    cols.IDS_BID_BLOCKS,
    cols.FLOAT_OBJECTIVE_VALUE,
    cols.BOOL_IS_EXPECTED_INCOME_RESPECTED,
    cols.SOLVER_RESULTS_COLUMN,
    cols.INT_MIC_SCOS_COUNT,
    cols.INT_BID_BLOCKS_COUNT,
    cols.INT_PARADOX_GROUPS_COUNT,
    cols.CLEARED_ENERGY_COLUMN,
    cols.CLEARING_PRICES_COLUMN,
    cols.SPAIN_PORTUGAL_TRANSMISSIONS_COLUMN,
]


COD_OFERTA_RESIDUAL_DEMAND_V = "RESIDUAL_DEMAND_V"
COD_OFERTA_RESIDUAL_DEMAND_C = "RESIDUAL_DEMAND_C"

CODIGO_UNIDAD_RESIDUAL_DEMAND_V = "RDC_V"
CODIGO_UNIDAD_RESIDUAL_DEMAND_C = "RDC_C"

RDC_CAB_V_BASE = {
    cols.ID_ORDER: COD_OFERTA_RESIDUAL_DEMAND_V,
    cols.ID_UNIDAD: CODIGO_UNIDAD_RESIDUAL_DEMAND_V,
    cols.CAT_BUY_SELL: "V",
    cols.FLOAT_MIC: 0.0,
    cols.FLOAT_MAX_POWER: 9999999999,
}
RDC_CAB_C_BASE = {
    cols.ID_ORDER: COD_OFERTA_RESIDUAL_DEMAND_C,
    cols.ID_UNIDAD: CODIGO_UNIDAD_RESIDUAL_DEMAND_C,
    cols.CAT_BUY_SELL: "C",
    cols.FLOAT_MIC: 0.0,
    cols.FLOAT_MAX_POWER: 9999999999,
}

RDC_ENERGY_COLUMNS = [f"energy_{i}" for i in range(1, 25)]
RDC_PRICE_COLUMNS = [f"price_{i}" for i in range(1, 25)]
